### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sorairoqueen** [sorairoqueen/protospace-36467#1]
#URL
https://protospace-36467.herokuapp.com/

**Comment by snkw-works** [comment]
@sorairoqueen さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できるよう修正しましょう**
ログアウト状態のユーザーにはプロトタイプ一覧が表示されない状態です。

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるよう修正しましょう**
コメントを空欄のまま送信すると、別のページに遷移してしまいます。
https://user-images.githubusercontent.com/54050089/135735523-271be119-e5d3-45f7-b979-bd63fd05f8b4.mov

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
コメント投稿者名をクリックすると、そのユーザーではなくプロトタイプ投稿者の詳細ページに遷移してしまいます。

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
ユーザー名が一部正しく表示されていない状態です。
<img width="1161" alt="スクリーンショット_2021-10-03_9_48_34" src="https://user-images.githubusercontent.com/54050089/135735614-eb33a72e-5d54-4c4a-abdf-1be3066bc2f5.png">

- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるよう修正しましょう**
ログアウト状態のユーザーがプロトタイプ詳細ページに遷移しようとすると、エラー画面に遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sorairoqueen** [comment]
@snkw-works 
動作確認いただきありがとうございました。
修正完了しました。
完了報告フォームも提出しましたので、ご確認よろしくお願いします。

> 修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！ ※新しいissueを作っていただく必要はございません。 https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by sorairoqueen** [comment]
@miyu-yamamoto 
動作確認ありがとうございました。

実装課題は復習するのに大変参考になりました。これを活かして最終課題に取り組んでいきます。

引き続きよろしくお願いします。
